"""Generate portable rule files from one source; standard library only."""

import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
FORMATS = {
    "agents": "AGENTS.md",
    "claude": "CLAUDE.md",
    "gemini": "GEMINI.md",
    "cursor": ".cursorrules",
    "windsurf": ".windsurfrules",
}


def version(root=ROOT):
    skill = (root / "SKILL.md").read_text(encoding="utf-8")
    match = re.search(r'^  version: "(\d+\.\d+\.\d+)"$', skill, re.MULTILINE)
    if not match:
        raise ValueError("SKILL.md needs a quoted metadata.version in x.y.z form")
    return match.group(1)


def render(root=ROOT):
    body = (root / "references/portable-rules.md").read_text(encoding="utf-8")
    return (
        f"<!-- Generated by scripts/build_rules.py; version {version(root)}. -->\n"
        "<!-- Edit references/portable-rules.md, then regenerate. -->\n\n"
        + body.rstrip() + "\n"
    )


def check_rules(root=ROOT):
    expected = render(root)
    errors = []
    for filename in FORMATS.values():
        path = root / "rules" / filename
        if not path.is_file():
            errors.append(f"Missing rule file: {path.relative_to(root)}")
        elif path.read_text(encoding="utf-8") != expected:
            errors.append(f"Rule drift: {path.relative_to(root)}; run scripts/build_rules.py")
    return errors


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        errors = check_rules()
        print("\n".join(errors) if errors else "All five rule files are current.")
        return bool(errors)
    output = render().encode("utf-8")
    (ROOT / "rules").mkdir(exist_ok=True)
    for filename in FORMATS.values():
        (ROOT / "rules" / filename).write_bytes(output)
    print("Generated five portable rule files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
